### ISSUE TITLE
Proposal: iterable_to_splfixedarray

### ISSUE THREAD

**Issue by tomkyle** [bpolaszek/php-iterable-functions#5]
When _iterable_to_traversable_ returns an ArrayIterator, a new _iterable_to_splfixedarray_ would perfectly complement the _iterable_to_*_ functions. Admittedly, that name is somehow bulky – but in pseudocode it would go like this:

```
function iterable_to_splfixedarray( $things )
{
  return \SplFixedArray::fromArray( iterable_to_array( $things ), "with_indexes" );
}
```
What do you think?

**Comment by bpolaszek** [comment]
Hello @tomkyle, 

Thank you for your interest to this library. 
Actually I'm not sure it's really worth it: the main advantage of a `SplFixedArray` is the write speed, which doesn't count when you come from an existing array.

Besides, the main purpose of this library is to solve common problems between arrays and Traversables. Converting iterables to other "handy" types is out of its scope (otherwise we could consider converting to CachedIterator, to SimpleXml or anything else).

Thank you,
Ben

**Comment by tomkyle** [comment]
Aye, thx for your fast reply!
